/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import org.mariuszgromada.math.mxparser.Expression;
import org.mariuszgromada.math.mxparser.mXparser;

/**
 *
 * @author nkaurelien
 */
public class Calculatrice extends javax.swing.JFrame {
    
    private Double result;
    private String operation = "";
    private Double memory;
    private boolean isCalculed = false;
    final List<String> items = new ArrayList<String>();

    /**
     * Creates new form Calculatrice
     */
    public Calculatrice() {
        initComponents();
        clearOperation();
        clearResult();
        hideMemoryMark();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_next = new javax.swing.JLabel();
        btn_memory_moins = new javax.swing.JLabel();
        btn_previous = new javax.swing.JLabel();
        btn_memory_rappel = new javax.swing.JLabel();
        btn_memory_plus = new javax.swing.JLabel();
        btn_memory_store = new javax.swing.JLabel();
        btn_memory_empty = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_mul = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        btn_moins = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_operations_history = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        btn_virgule = new javax.swing.JButton();
        btn_plusoumoins = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn_pow = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        jPanel_ecran = new javax.swing.JPanel();
        jTextField_operation = new javax.swing.JTextField();
        jLabel_resultat = new javax.swing.JLabel();
        jLabel_memory_mark = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(19, 43, 13));
        jLabel1.setText("Copyright 2017 - NEAA Intelligence");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 380, 20));

        jPanel4.setBackground(new java.awt.Color(34, 32, 34));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_next.setBackground(new java.awt.Color(226, 226, 226));
        btn_next.setForeground(new java.awt.Color(102, 32, 199));
        btn_next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/131_1.png"))); // NOI18N
        btn_next.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_next.setOpaque(true);
        btn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nextMouseClicked(evt);
            }
        });
        jPanel4.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 42, 32));

        btn_memory_moins.setBackground(new java.awt.Color(173, 156, 96));
        btn_memory_moins.setForeground(new java.awt.Color(102, 32, 199));
        btn_memory_moins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_memory_moins.setText("M-");
        btn_memory_moins.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_memory_moins.setOpaque(true);
        btn_memory_moins.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_memory_moins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_memory_moinsMouseReleased(evt);
            }
        });
        jPanel4.add(btn_memory_moins, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 42, 32));

        btn_previous.setBackground(new java.awt.Color(226, 226, 226));
        btn_previous.setForeground(new java.awt.Color(102, 32, 199));
        btn_previous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/132_1.png"))); // NOI18N
        btn_previous.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_previous.setOpaque(true);
        btn_previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_previousMouseClicked(evt);
            }
        });
        jPanel4.add(btn_previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 42, 32));

        btn_memory_rappel.setBackground(new java.awt.Color(173, 156, 96));
        btn_memory_rappel.setForeground(new java.awt.Color(102, 32, 199));
        btn_memory_rappel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_memory_rappel.setText("MR");
        btn_memory_rappel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_memory_rappel.setOpaque(true);
        btn_memory_rappel.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_memory_rappel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_memory_rappelMouseReleased(evt);
            }
        });
        jPanel4.add(btn_memory_rappel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 42, 32));

        btn_memory_plus.setBackground(new java.awt.Color(173, 156, 96));
        btn_memory_plus.setForeground(new java.awt.Color(102, 32, 199));
        btn_memory_plus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_memory_plus.setText("M+");
        btn_memory_plus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_memory_plus.setOpaque(true);
        btn_memory_plus.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_memory_plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_memory_plusMouseReleased(evt);
            }
        });
        jPanel4.add(btn_memory_plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 42, 32));

        btn_memory_store.setBackground(new java.awt.Color(173, 156, 96));
        btn_memory_store.setForeground(new java.awt.Color(102, 32, 199));
        btn_memory_store.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_memory_store.setText("MS");
        btn_memory_store.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_memory_store.setOpaque(true);
        btn_memory_store.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_memory_store.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_memory_storeMouseReleased(evt);
            }
        });
        jPanel4.add(btn_memory_store, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 42, 32));

        btn_memory_empty.setBackground(new java.awt.Color(173, 156, 96));
        btn_memory_empty.setForeground(new java.awt.Color(102, 32, 199));
        btn_memory_empty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_memory_empty.setText("MC");
        btn_memory_empty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_memory_empty.setOpaque(true);
        btn_memory_empty.setPreferredSize(new java.awt.Dimension(24, 24));
        btn_memory_empty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_memory_emptyMouseReleased(evt);
            }
        });
        jPanel4.add(btn_memory_empty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 42, 32));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 50));

        jPanel3.setBackground(new java.awt.Color(34, 32, 34));

        btn_mul.setText("*");
        btn_mul.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulActionPerformed(evt);
            }
        });

        btn_div.setText("/");
        btn_div.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_plus.setText("+");
        btn_plus.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });

        btn_moins.setText("-");
        btn_moins.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_moins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moinsActionPerformed(evt);
            }
        });

        jButton5.setText("=");
        jButton5.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btn_mod.setText("%");
        btn_mod.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        jButton10.setText("ANS");
        jButton10.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btn11.setText(")");
        btn11.setPreferredSize(new java.awt.Dimension(32, 32));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setText("(");
        btn12.setPreferredSize(new java.awt.Dimension(32, 32));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_moins, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_moins, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 130, 270));

        jList_operations_history.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_operations_history.setFocusable(false);
        jScrollPane1.setViewportView(jList_operations_history);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 380, 50));

        jPanel2.setBackground(new java.awt.Color(34, 32, 34));

        btn0.setText("0");
        btn0.setPreferredSize(new java.awt.Dimension(32, 32));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.setPreferredSize(new java.awt.Dimension(32, 32));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.setPreferredSize(new java.awt.Dimension(32, 32));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        B1.setText("1");
        B1.setPreferredSize(new java.awt.Dimension(32, 32));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        btn_virgule.setText(".");
        btn_virgule.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_virgule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_virguleActionPerformed(evt);
            }
        });

        btn_plusoumoins.setBackground(new java.awt.Color(58, 70, 105));
        btn_plusoumoins.setText("-/+");
        btn_plusoumoins.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_plusoumoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusoumoinsActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.setPreferredSize(new java.awt.Dimension(32, 32));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.setPreferredSize(new java.awt.Dimension(32, 32));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        B2.setText("2");
        B2.setPreferredSize(new java.awt.Dimension(32, 32));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.setPreferredSize(new java.awt.Dimension(32, 32));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.setPreferredSize(new java.awt.Dimension(32, 32));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.setPreferredSize(new java.awt.Dimension(32, 32));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.setBackground(new java.awt.Color(254, 160, 160));
        btn10.setText("C");
        btn10.setPreferredSize(new java.awt.Dimension(32, 32));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/106.png"))); // NOI18N
        btn13.setPreferredSize(new java.awt.Dimension(32, 32));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn_pow.setBackground(new java.awt.Color(58, 70, 105));
        btn_pow.setText("^");
        btn_pow.setToolTipText("puissance");
        btn_pow.setPreferredSize(new java.awt.Dimension(32, 32));
        btn_pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_powActionPerformed(evt);
            }
        });

        btn00.setBackground(new java.awt.Color(58, 70, 105));
        btn00.setText("00");
        btn00.setToolTipText("puissance");
        btn00.setPreferredSize(new java.awt.Dimension(32, 32));
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_virgule, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_plusoumoins, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_pow, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pow, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_plusoumoins, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_virgule, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 240, 270));

        jPanel_ecran.setBackground(new java.awt.Color(153, 140, 169));
        jPanel_ecran.setOpaque(false);

        jTextField_operation.setBackground(new java.awt.Color(179, 239, 133));
        jTextField_operation.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jTextField_operation.setForeground(new java.awt.Color(16, 66, 1));
        jTextField_operation.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_operation.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_operation.setOpaque(false);
        jTextField_operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_operationActionPerformed(evt);
            }
        });
        jTextField_operation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_operationKeyTyped(evt);
            }
        });

        jLabel_resultat.setFont(new java.awt.Font("Noto Sans", 0, 30)); // NOI18N
        jLabel_resultat.setForeground(new java.awt.Color(137, 142, 89));
        jLabel_resultat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_resultat.setText("resultat");

        jLabel_memory_mark.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel_memory_mark.setText("M");

        javax.swing.GroupLayout jPanel_ecranLayout = new javax.swing.GroupLayout(jPanel_ecran);
        jPanel_ecran.setLayout(jPanel_ecranLayout);
        jPanel_ecranLayout.setHorizontalGroup(
            jPanel_ecranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ecranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ecranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ecranLayout.createSequentialGroup()
                        .addComponent(jLabel_memory_mark)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jTextField_operation))
                .addContainerGap())
        );
        jPanel_ecranLayout.setVerticalGroup(
            jPanel_ecranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ecranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_operation, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ecranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_memory_mark))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel_ecran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bg.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_operationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_operationActionPerformed

    private void btn_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulActionPerformed
        setOperation("*");

    }//GEN-LAST:event_btn_mulActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        setOperation("1");
    }//GEN-LAST:event_B1ActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        setOperation("/");
    }//GEN-LAST:event_btn_divActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        setOperation("2");
    }//GEN-LAST:event_B2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        setOperation("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        setOperation("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        setOperation("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        setOperation("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        setOperation("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        setOperation("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        setOperation("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn_virguleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_virguleActionPerformed
        setOperation(",");
    }//GEN-LAST:event_btn_virguleActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        setOperation("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        clearOperation();
        clearResult();
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn_memory_rappelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memory_rappelMouseReleased
        result = memory;
        jLabel_resultat.setText(result.toString());
    }//GEN-LAST:event_btn_memory_rappelMouseReleased

    private void btn_memory_moinsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memory_moinsMouseReleased
        memory -= result;
        setResult(memory);

    }//GEN-LAST:event_btn_memory_moinsMouseReleased

    private void btn_memory_plusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memory_plusMouseReleased
        memory += result;
        setResult(memory);
    }//GEN-LAST:event_btn_memory_plusMouseReleased

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
        setOperation("+");
    }//GEN-LAST:event_btn_plusActionPerformed

    private void btn_plusoumoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusoumoinsActionPerformed
        if (result != 0) {
            setResult(result * -1);
        }
    }//GEN-LAST:event_btn_plusoumoinsActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (result != 0) {
            setOperation(result.toString());
        }
        int pas = result.toString().length();
        jTextField_operation.setCaretPosition(pas);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btn_moinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moinsActionPerformed
        setOperation("-");
    }//GEN-LAST:event_btn_moinsActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        setOperation(")");
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        setOperation("(");
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn_memory_storeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memory_storeMouseReleased
        memory = result;
        showMemoryMark();
    }//GEN-LAST:event_btn_memory_storeMouseReleased

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        setOperation("%");
    }//GEN-LAST:event_btn_modActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        calculer();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        String op;
        op = jTextField_operation.getText().substring(0, jTextField_operation.getText().length() - 1);
        jTextField_operation.setText(op);
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn_memory_emptyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_memory_emptyMouseReleased
        memory = 0.0;
        hideMemoryMark();
    }//GEN-LAST:event_btn_memory_emptyMouseReleased

    private void jTextField_operationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_operationKeyTyped
        List<Character> operators = new ArrayList<Character>();
        operators.add('+');
        operators.add('-');
        operators.add('*');
        operators.add('/');
        operators.add('%');
        operators.add(')');
        operators.add('(');
        operators.add('^');
        
        Character key = evt.getKeyChar();
        
        if (KeyEvent.VK_ENTER == key.charValue()) {
            calculer();
        } else {
            if (Character.isDigit(key.charValue()) || key.charValue() == KeyEvent.VK_BACK_SPACE || operators.contains(key)) {
            } else {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jTextField_operationKeyTyped

    private void btn_previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_previousMouseClicked
        moveCaretBy(-1);
        
    }//GEN-LAST:event_btn_previousMouseClicked

    private void btn_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseClicked
        moveCaretBy(1);
    }//GEN-LAST:event_btn_nextMouseClicked

    private void btn_powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_powActionPerformed
        setOperation("^");
    }//GEN-LAST:event_btn_powActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        setOperation("00");
    }//GEN-LAST:event_btn00ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
         try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         if ("Nimbus".equals(info.getName())) {
         javax.swing.UIManager.setLookAndFeel(info.getClassName());
         break;
         }
         }
         } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Calculatrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         */
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Calculatrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JLabel BG;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_div;
    private javax.swing.JLabel btn_memory_empty;
    private javax.swing.JLabel btn_memory_moins;
    private javax.swing.JLabel btn_memory_plus;
    private javax.swing.JLabel btn_memory_rappel;
    private javax.swing.JLabel btn_memory_store;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_moins;
    private javax.swing.JButton btn_mul;
    private javax.swing.JLabel btn_next;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton btn_plusoumoins;
    private javax.swing.JButton btn_pow;
    private javax.swing.JLabel btn_previous;
    private javax.swing.JButton btn_virgule;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_memory_mark;
    private javax.swing.JLabel jLabel_resultat;
    private javax.swing.JList jList_operations_history;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_ecran;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_operation;
    // End of variables declaration//GEN-END:variables

    private void setOperation(String string) {
        if (isCalculed) {
            jTextField_operation.setText("");
            isCalculed = false;
        }
        operation = jTextField_operation.getText();
        int pos = jTextField_operation.getCaretPosition();
        operation = operation.substring(0, pos) + string + operation.substring(pos);
        jTextField_operation.setText(operation);
        jTextField_operation.setCaretPosition(pos + 1);
    }
    
    private void clearOperation() {
        operation = "";
        jTextField_operation.setText(operation);
    }
    
    private void clearResult() {
        result = 0.0;
        jLabel_resultat.setText("0");
    }
    
    public Double getResult() {
        return result;
    }
    
    public void setResult(Double result) {
        this.result = result;
        jLabel_resultat.setText(result.toString());
    }
    
    private void calculer() {
        /*
         Expression e = new Expression("2*(32-4)");
         mXparser.consolePrintln("Res: " + e.getExpressionString() + " = " + e.calculate());
         //System.out.println("result "+ Outils.math.MathImpl.eval("((4 - 2^3 + 1) * -sqrt(3*3+4*4)) / 2"));
         */
        operation = jTextField_operation.getText();
        String exp = operation;
        Expression e = new Expression(exp.replace(',', '.'));
        result = e.calculate();
        isCalculed = true;
        if (result.isNaN()) {
            jLabel_resultat.setText("Operation erronée");
        } else {
            jLabel_resultat.setText(result.toString());
            mXparser.consolePrintln("Res: " + e.getExpressionString() + " = " + e.calculate());
            items.add("Res: " + e.getExpressionString() + " = " + e.calculate());
            jList_operations_history.setModel(new javax.swing.AbstractListModel() {
                
                List<String> strings = items;

                public int getSize() {
                    return strings.size();
                }

                public Object getElementAt(int i) {
                    return strings.get(i);
                }
            });
        }

    }

    /**
     *
     * @param pas nombre de pas pour deplacer le curseur du text -1 signifie
     * saute 1 charatere a gauche 1 signifie saute 1 charatere a droite
     */
    private void moveCaretBy(int pas) {
        int pos = jTextField_operation.getCaretPosition();
        jTextField_operation.setCaretPosition(pos + pas);
    }

    private void showMemoryMark() {
        jLabel_memory_mark.setVisible(true);
    }

    private void hideMemoryMark() {
        jLabel_memory_mark.setVisible(false);
    }
    
}
